# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kvm-exporter.fullname" . }}
  labels:
    name: {{ include "kvm-exporter.fullname" . }}
    {{- with .Values.serviceMonitorLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ include "kvm-exporter.fullname" . }}
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
