# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  name: {{ include "kvm-exporter.fullname" . }}
  labels:
    app: {{ include "kvm-exporter.fullname" . }}
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  selector:
    app: {{ include "kvm-exporter.fullname" . }}
  type: ClusterIP
