# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0
apiVersion: greenhouse.sap/v1alpha1
kind: PluginDefinition
metadata:
  name: kvm-node-agent
spec:
  version: 1.0.0
  displayName: Labels Injector
  description: "KVM Node Agent to manage KVM hypervisor nodes within a Kubernetes environment."
  helmChart:
    name: kvm-node-agent
    repository: ghcr.io/cobaltcore-dev/kvm-node-agent
    version: 1.0.0