# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: kvm-exporter
description: A Helm chart for Kubernetes
type: application
<<<<<<< HEAD
version: 0.3.1
appVersion: latest
=======
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.0
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "latest"
>>>>>>> 5e5d0e6 (chore(kvm-exporter): bump version to 0.3.0)
